### ISSUE TITLE
Tournaments/tree

### ISSUE THREAD

**Issue by Flo4l** [Plotogandr/AdessoKicker#12]
Tournaments/<>/tree

Browser
There was an unexpected error (type=Internal Server Error, status=500).
An error happened during template parsing (template: "class path resource [templates/tournament/tree.html]")

Eclipse
org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'tournamentTree' cannot be found on object of type 'de.adesso.kicker.tournament.singleelimination.SingleElimination' - maybe not public or not valid?

**Comment by Plotogandr** [comment]
Please pull the newest version, where were some fundamental changes in how the brackets/trees are saved, see https://github.com/Plotogandr/AdessoKicker/pull/15. Check if the issue persists in the newest version. Make sure to delete your existing DB before. (If you're using eclipse delete it through the windows explorer)
